# Generated by Django 4.1.7 on 2023-03-26 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_category'),
        ('store', '0006_category'),
    ]

    operations = [
    ]
