# Generated by Django 4.1.7 on 2023-03-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(max_length=20, verbose_name='Stock Keeping Unit'),
        ),
    ]
